version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: __TASK_DEFINITION_ARN__
        LoadBalancerInfo:
          ContainerName: "karthik-strapi"
          ContainerPort: 1337