name: Docker Build and Push

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up environment variables
        run: echo "GITHUB_SHA=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t strapi-app:latest -t duggana1994/strapi-app:${{ github.sha }} .

      - name: Push Docker images
        run: |
          docker push duggana1994/strapi-app:${{ github.sha }}


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Render new ECS Task Definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: karthik-strapi
          image: duggana1994/strapi-app:${{ github.sha }}

      - name: Deploy to ECS using CodeDeploy
        uses: aws-actions/aws-codedeploy-deploy-application@v1
        with:
          application-name: karthik-codedeploy-app
          deployment-group: karthik-deployment-group
          task-definition: ${{ steps.render-task-def.outputs.task-definition-arn }}
          appspec: appspec.yml